### ISSUE TITLE
WIKI

### ISSUE THREAD

**Issue by xinparkn** [MissYourSmile/specialist_info#1]
大佬的项目 想学习一下 请问怎么才能跑起来呢 包括用的包

**Comment by MissYourSmile** [comment]
你好，感谢关注，REMEDE已更新。
这个是我在学校时课程设计的作业，比较粗糙，如果你想用它来应付课程设计的话应该是可以的，
如果你想学习 python django 的话，这个项目可以做一个参考，但有些地方的实现不一定是最好的选择，因为我自己并不是一个熟练的python使用者。
这个项目截止当时课程设计验收完之后也就没有更新了，估计后面也难有时间去更新，欢迎fork并进一步完善它。
谢谢！

**Comment by xinparkn** [comment]
非常感谢。 
ok
正在学习Django中
